### ISSUE TITLE
[DOCS] ADD SECURITY POLICY

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/coronavirus-blocker-extension#29]
Please add a SECURITY POLICY like

**[Security Policy from Another Project](https://github.com/KendallDoesCoding/mogul-christmas/security/policy)**

**Comment by HarshAg90** [comment]
can i work on this, if so, can you provide "privacy terms" and Email address
and also form for if you want

**Comment by KendallDoesCoding** [comment]
> can i work on this, if so, can you provide "privacy terms" and Email address and also form for if you want

Sure! There doesn't need to be any security terms, just something like the example I shared above, email and form, email and form link is the same!
