### ISSUE TITLE
[URGENT] Update Manifest Version

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/coronavirus-blocker-extension#32]
"Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details."

The extension uses Manifest Version 2 which is going to be removed this year. We need to update the manifest version.

**Comment by Srinja333** [comment]
can i work on this?

**Comment by KendallDoesCoding** [comment]
> can i work on this?

Sure!
